server: 
  port: 8081
spring: 
  application: 
    name: theater-service
  zipkin:
    enabled: true    
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: "jdbc:mysql://localhost:3306/movies?createDatabaseIfNotExist=true"
    username: root
  jpa: 
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate: 
      ddl-auto: update
  session: 
    jdbc: 
      initialize-schema: always
    store-type: jdbc
    timeout: 
      seconds: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka    
      
logging:
    level:
        com:
            theater: DEBUG
        root: WARN    
    file:     
      name: 'E:/movie-app-logs/logs/elk/elk-stack.log'   
      
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'           
