spring:
  application: 
    name: api-gateway-service
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
      - id: movieModule
        uri: lb://movie-service
        predicates:
        - Path=/movie/**
      - id: theaterModule
        uri: lb://theater-service
        predicates:
        - Path=/theater/**
      - id: bookingModule
        uri: lb://booking-service
        predicates:
        - Path=/booking/**
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://localhost:8080/auth/realms/My-Realm
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            scope: openid
            client-id: spring-gateway-client
            client-secret: 3RhEF8pqKTANrQ6BhfxaYVmcjTXsDK0u
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

# Enable these to debug the Authorization flow
logging:
    level:
      org:
        springframework:
          security:
            web: DEBUG
server:
  port: 7000

        
eureka:
  server:
    peer-node-read-timeout-ms: 25000
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka        
      
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus          