variables:
  VERSION: 1.0.0

stages:
- lint
- release
- deploy

sonar:
  stage: lint
  image: maven:3.6.0-jdk-8
  script:
  - mvn -f movie-service/pom.xml clean install -s movie-service/settings.xml sonar:sonar -Dmaven.test.failure.ignore=true

build image:
  stage: release
  image: docker:stable
  services:
  - docker:dind
  script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  - docker build -t ${CI_REGISTRY_IMAGE}:${VERSION} .
  - docker push ${CI_REGISTRY_IMAGE}:${VERSION}
  only:
  - master@movie-booking-app/booking-movie-service/movie-service
  

deploy to server:
  stage: deploy
  image: registry.companyname.com:443/project-name/kube-client:1.0.0
  script:
  - kubectl --insecure-skip-tls-verify  get pods
  only:
  - master@movie-booking-app/booking-movie-service/movie-service
  
